// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQk4Qq69wr3JEKZHdRm3kBBS1d5kRrRo',
    appId: '1:981627375813:web:d92df1bf460604ecc0a0ac',
    messagingSenderId: '981627375813',
    projectId: 'listly-f1ab7',
    authDomain: 'listly-f1ab7.firebaseapp.com',
    storageBucket: 'listly-f1ab7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZtX9bDfmntNikHbfxE_nqOe2oTiyhDqc',
    appId: '1:981627375813:android:b6886aeaa5644818c0a0ac',
    messagingSenderId: '981627375813',
    projectId: 'listly-f1ab7',
    storageBucket: 'listly-f1ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8-p3WIomVZxMfHT7GDyLxmmT-oLzuaA',
    appId: '1:981627375813:ios:d572070d77f53da7c0a0ac',
    messagingSenderId: '981627375813',
    projectId: 'listly-f1ab7',
    storageBucket: 'listly-f1ab7.appspot.com',
    iosClientId:
        '981627375813-k1dndnig9nbufjkg4th63asv46bmfqkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientwebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU8-p3WIomVZxMfHT7GDyLxmmT-oLzuaA',
    appId: '1:981627375813:ios:d572070d77f53da7c0a0ac',
    messagingSenderId: '981627375813',
    projectId: 'listly-f1ab7',
    storageBucket: 'listly-f1ab7.appspot.com',
    iosClientId:
        '981627375813-k1dndnig9nbufjkg4th63asv46bmfqkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientwebapp',
  );
}
